import { useEffect,useState,type FormEvent } from 'react';import { Button } from '../ui/Button';import { Card } from '../ui/Card';
import type { Organization,OrganizationInput } from '../../organization/types';
export function OrganizationForm({organization,onSave,editable}:{organization:Organization;onSave?:(input:OrganizationInput)=>Promise<void>;editable:boolean}){
 const [form,setForm]=useState<OrganizationInput>({name:'',industry:'',website:'',contactEmail:'',phone:'',address:''});const [errors,setErrors]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [feedback,setFeedback]=useState('');
 useEffect(()=>{setForm({name:organization.name,industry:organization.industry,website:organization.website,contactEmail:organization.contactEmail,phone:organization.phone,address:organization.address});},[organization]);
 function set<K extends keyof OrganizationInput>(key:K,value:OrganizationInput[K]){setForm(current=>({...current,[key]:value}));setFeedback('');}
 async function submit(event:FormEvent){event.preventDefault();const next:Record<string,string>={};if(!form.name.trim())next.name='Enter an organization name.';if(form.contactEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.contactEmail.trim()))next.contactEmail='Enter a valid email address.';if(form.website){try{const url=new URL(form.website);if(!['http:','https:'].includes(url.protocol))throw new Error();}catch{next.website='Enter a valid website URL, including https://.';}}setErrors(next);if(Object.keys(next).length)return;setSaving(true);setFeedback('');try{await onSave?.({...form,name:form.name.trim(),contactEmail:form.contactEmail.trim(),website:form.website.trim()});setFeedback('Organization details updated.');}catch{setFeedback('Unable to save organization details. Please try again.');}finally{setSaving(false);}}
 function reset(){setForm({name:organization.name,industry:organization.industry,website:organization.website,contactEmail:organization.contactEmail,phone:organization.phone,address:organization.address});setErrors({});setFeedback('');}
 return <form className="organization-form" onSubmit={submit} noValidate><Card className="organization-form-card"><div className="form-section-heading"><div><p className="eyebrow">ORGANIZATION PROFILE</p><h2>Organization information</h2><p>Details used to identify your workspace.</p></div><span className="data-label">MOCK DATA</span></div><div className="organization-fields"><label className="form-field"><span>Organization name</span><input value={form.name} onChange={e=>set('name',e.target.value)} disabled={!editable} aria-invalid={Boolean(errors.name)}/>{errors.name&&<small className="field-error">{errors.name}</small>}</label><label className="form-field"><span>Industry</span><input value={form.industry} onChange={e=>set('industry',e.target.value)} disabled={!editable}/></label><label className="form-field"><span>Website</span><input inputMode="url" placeholder="https://example.com" value={form.website} onChange={e=>set('website',e.target.value)} disabled={!editable} aria-invalid={Boolean(errors.website)}/>{errors.website&&<small className="field-error">{errors.website}</small>}</label><label className="form-field"><span>Contact email</span><input inputMode="email" value={form.contactEmail} onChange={e=>set('contactEmail',e.target.value)} disabled={!editable} aria-invalid={Boolean(errors.contactEmail)}/>{errors.contactEmail&&<small className="field-error">{errors.contactEmail}</small>}</label><label className="form-field"><span>Phone</span><input type="tel" value={form.phone} onChange={e=>set('phone',e.target.value)} disabled={!editable}/></label><label className="form-field address-field"><span>Address</span><textarea rows={3} value={form.address} onChange={e=>set('address',e.target.value)} disabled={!editable}/></label></div>{feedback&&<p className="inline-feedback" role="status">{feedback}</p>}<div className="organization-form-footer"><span>Changes are stored locally in this preview.</span>{editable&&onSave&&<div><Button variant="secondary" type="button" onClick={reset} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':'Save changes'}</Button></div>}</div></Card></form>;
}


