from alembic import op
import sqlalchemy as sa
revision='0001_initial_schema'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('organizations', sa.Column('id',sa.String(36),primary_key=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('industry',sa.String(200),nullable=False),sa.Column('location',sa.String(200),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
    op.create_table('permissions', sa.Column('id',sa.String(36),primary_key=True),sa.Column('resource',sa.String(80),nullable=False),sa.Column('action',sa.String(80),nullable=False),sa.UniqueConstraint('resource','action',name='uq_permission_resource_action'))
    op.create_table('roles', sa.Column('id',sa.String(36),primary_key=True),sa.Column('name',sa.String(80),unique=True,nullable=False),sa.Column('description',sa.String(255)))
    op.create_table('users', sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('email',sa.String(320),unique=True,nullable=False),sa.Column('password_hash',sa.String(500),nullable=False),sa.Column('status',sa.String(20),nullable=False,server_default='ACTIVE'),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
    op.create_index('ix_users_org','users',['organization_id']); op.create_index('ix_users_status','users',['status'])
    op.create_table('user_roles',sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id',ondelete='CASCADE'),primary_key=True),sa.Column('role_id',sa.String(36),sa.ForeignKey('roles.id',ondelete='CASCADE'),primary_key=True))
    op.create_table('role_permissions',sa.Column('role_id',sa.String(36),sa.ForeignKey('roles.id',ondelete='CASCADE'),primary_key=True),sa.Column('permission_id',sa.String(36),sa.ForeignKey('permissions.id',ondelete='CASCADE'),primary_key=True))
    op.create_table('sessions',sa.Column('id',sa.String(36),primary_key=True),sa.Column('user_id',sa.String(36),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('jti',sa.String(64),unique=True,nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False)); op.create_index('ix_sessions_user','sessions',['user_id']); op.create_index('ix_sessions_jti','sessions',['jti'])
    op.create_table('customers',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('company',sa.String(200),nullable=False),sa.Column('type',sa.String(50),nullable=False),sa.Column('industry',sa.String(200),nullable=False),sa.Column('location',sa.String(200),nullable=False),sa.Column('status',sa.String(20),server_default='Active',nullable=False),sa.Column('last_contact_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
    op.create_index('ix_customers_org','customers',['organization_id']); op.create_index('ix_customers_status','customers',['status'])
    op.create_table('leads',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('company',sa.String(200),nullable=False),sa.Column('contact_name',sa.String(200),nullable=False),sa.Column('status',sa.String(50),server_default='NEW',nullable=False),sa.Column('value',sa.Numeric(14,2),server_default='0',nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False)); op.create_index('ix_leads_org_status','leads',['organization_id','status'])
    op.create_table('quotes',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('customer_name',sa.String(200),nullable=False),sa.Column('status',sa.String(50),server_default='DRAFT',nullable=False),sa.Column('amount',sa.Numeric(14,2),server_default='0',nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False)); op.create_index('ix_quotes_org_status','quotes',['organization_id','status'])
    op.create_table('audit_logs',sa.Column('id',sa.String(36),primary_key=True),sa.Column('organization_id',sa.String(36),sa.ForeignKey('organizations.id'),nullable=False),sa.Column('actor_user_id',sa.String(36),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('actor_email',sa.String(320)),sa.Column('action',sa.String(80),nullable=False),sa.Column('resource',sa.String(80),nullable=False),sa.Column('resource_id',sa.String(100)),sa.Column('result',sa.String(20),nullable=False),sa.Column('before_state',sa.JSON),sa.Column('after_state',sa.JSON),sa.Column('ip_address',sa.String(80)),sa.Column('user_agent',sa.String(500)),sa.Column('extra',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False))
    op.create_index('ix_audit_org_created','audit_logs',['organization_id','created_at']); op.create_index('ix_audit_actor_created','audit_logs',['actor_user_id','created_at']); op.create_index('ix_audit_action_result_created','audit_logs',['action','result','created_at']); op.create_index('ix_audit_resource','audit_logs',['resource','resource_id'])
    op.execute("CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit_logs is append-only'; END; $$;")
    op.execute("CREATE TRIGGER audit_logs_append_only BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();")
def downgrade(): op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs"); op.execute("DROP FUNCTION IF EXISTS prevent_audit_mutation()"); op.drop_table('audit_logs'); op.drop_table('quotes'); op.drop_table('leads'); op.drop_table('customers'); op.drop_table('sessions'); op.drop_table('role_permissions'); op.drop_table('user_roles'); op.drop_table('users'); op.drop_table('roles'); op.drop_table('permissions'); op.drop_table('organizations')
