import { useCallback, useEffect, useMemo, useState } from 'react';
import { Badge } from '../components/ui/Badge'; import { Button } from '../components/ui/Button'; import { Card } from '../components/ui/Card'; import { Dialog } from '../components/ui/Dialog';
import { listAuditLogs } from '../audit/auditService'; import { useFeedback } from '../feedback/FeedbackProvider'; import type { AuditFilters, AuditLog } from '../audit/types';
const initial: AuditFilters = { query:'', action:'All', resource:'All', status:'All', date:'All time', user:'All' };
const actions = ['All','Created','Updated','Deleted','Login','Logout']; const resources = ['All','Customer','Lead','Deal','Quote','Order','User','Organization','Authentication'];
function stamp(value:string) { return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)); }
export function AuditPage() {
 const {beginLoading}=useFeedback(); const [filters,setFilters]=useState(initial); const [logs,setLogs]=useState<AuditLog[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false); const [selected,setSelected]=useState<AuditLog|null>(null);
 const load=useCallback(async()=>{const finish=beginLoading();setLoading(true);setError(false);try{setLogs(await listAuditLogs(filters));}catch{setError(true);}finally{setLoading(false);finish();}},[filters,beginLoading]);
 useEffect(()=>{void load();},[load]); const users=useMemo(()=>['All',...new Set(logs.map(log=>log.userName))],[logs]); const set=(key:keyof AuditFilters,value:string)=>setFilters(current=>({...current,[key]:value}));
 return <div className="page management-page audit-page"><div className="page-heading"><div><p className="eyebrow">WORKSPACE <span className="heading-dot">·</span> OVERSIGHT</p><h1>Audit logs</h1><p className="page-subtitle">Track important activity across the organization.</p></div><span className="data-label">MOCK DATA</span></div>
 <Card className="audit-card"><div className="audit-toolbar"><label className="audit-search"><span aria-hidden="true">⌕</span><input value={filters.query} onChange={e=>set('query',e.target.value)} placeholder="Search audit logs..." aria-label="Search audit logs by user, action, resource or description"/></label><label className="filter-label">Date <select value={filters.date} onChange={e=>set('date',e.target.value)}>{['All time','Today','Last 7 days','Last 30 days'].map(x=><option key={x}>{x}</option>)}</select></label><label className="filter-label">User <select value={filters.user} onChange={e=>set('user',e.target.value)}>{users.map(x=><option key={x}>{x}</option>)}</select></label><label className="filter-label">Action <select value={filters.action} onChange={e=>set('action',e.target.value)}>{actions.map(x=><option key={x}>{x}</option>)}</select></label><label className="filter-label">Resource <select value={filters.resource} onChange={e=>set('resource',e.target.value)}>{resources.map(x=><option key={x}>{x}</option>)}</select></label><label className="filter-label">Status <select value={filters.status} onChange={e=>set('status',e.target.value)}>{['All','Success','Failed'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 {error?<div className="load-error" role="alert"><h2>Unable to load audit logs</h2><p>Something went wrong while retrieving activity.</p><Button variant="secondary" onClick={()=>void load()}>Try again</Button></div>:loading?<div className="table-skeleton" role="status" aria-label="Loading audit logs">{Array.from({length:5},(_,i)=><div className="audit-skeleton-row" key={i}><i/><i/><i/><i/><i/></div>)}</div>:logs.length===0?<div className="empty-state"><span className="empty-mark">⌕</span><h3>No activity found</h3><p>Try adjusting your filters or search criteria.</p></div>:<div className="table-scroll"><table className="audit-table"><thead><tr><th scope="col">Timestamp</th><th scope="col">User</th><th scope="col">Action</th><th scope="col">Resource</th><th scope="col">Description</th><th scope="col">Status</th></tr></thead><tbody>{logs.map(log=><tr key={log.id} tabIndex={0} onClick={()=>setSelected(log)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(log);}}} aria-label={`View audit event: ${log.description}`}><td className="audit-time">{stamp(log.timestamp)}</td><td><strong>{log.userName}</strong></td><td>{log.action}</td><td>{log.resource}</td><td>{log.description}</td><td><Badge tone={log.status==='success'?'green':'red'}>{log.status==='success'?'Success':'Failed'}</Badge></td></tr>)}</tbody></table></div>}
 {!loading&&!error&&<div className="table-footer">Showing {logs.length} {logs.length===1?'event':'events'} <span>Activity history · Temporary mock data</span></div>}</Card>
 <Dialog open={Boolean(selected)} title="Audit event" onClose={()=>setSelected(null)}><dl className="user-detail-list audit-detail">{selected&&<><div><dt>Timestamp</dt><dd>{stamp(selected.timestamp)}</dd></div><div><dt>User</dt><dd>{selected.userName}</dd></div><div><dt>Action</dt><dd>{selected.action}</dd></div><div><dt>Resource</dt><dd>{selected.resource}</dd></div><div><dt>Resource ID</dt><dd>{selected.resourceId||'—'}</dd></div><div><dt>Description</dt><dd>{selected.description}</dd></div><div><dt>Status</dt><dd><Badge tone={selected.status==='success'?'green':'red'}>{selected.status==='success'?'Success':'Failed'}</Badge></dd></div></>}</dl></Dialog>
 </div>;
}

