import { useState } from 'react';
import { Card } from '../components/ui/Card';import { Badge } from '../components/ui/Badge';import { Button } from '../components/ui/Button';import { formatCurrency } from '../lib/utils';
const metrics=[{label:'Total customers',value:'248',delta:'+12%',icon:'♧',note:'vs. last month'},{label:'Active leads',value:'86',delta:'+18%',icon:'⌁',note:'vs. last month'},{label:'Open deals',value:'32',delta:'+8%',icon:'◇',note:'vs. last month'},{label:'Pending quotes',value:'14',delta:'3 due soon',icon:'▧',note:'across 8 accounts'},{label:'Pipeline value',value:formatCurrency(12400000),delta:'+24%',icon:'↗',note:'vs. last month'}];
const activity=[{initials:'AV',name:'Amit Verma',action:'moved a deal to',target:'Negotiation',time:'12 min ago'},{initials:'PS',name:'Priya Shah',action:'sent a quote to',target:'Aarti Chemicals',time:'48 min ago'},{initials:'KM',name:'Karan Mehta',action:'added a new lead',target:'from a trade fair',time:'2 hours ago'},{initials:'SI',name:'Sneha Iyer',action:'uploaded a compliance document for',target:'Tata Chemicals',time:'3 hours ago'}];
const bars=[42,56,46,66,58,75,62,86,71,91,77,100];
export function Dashboard(){const [range,setRange]=useState('This month');return <div className="page dashboard-page">
 <div className="page-heading dashboard-heading"><div><p className="eyebrow">WEDNESDAY, 30 SEPTEMBER 2026 <span className="heading-dot">·</span> YOUR WORKSPACE</p><h1>Good morning, Riddima <span className="wave">✳</span></h1><p className="page-subtitle">Here’s what’s happening across your chemical business today.</p></div><label className="range-select"><span className="sr-only">Reporting period</span><select value={range} onChange={e=>setRange(e.target.value)}><option>This month</option><option>This quarter</option><option>This year</option></select><span>⌄</span></label></div>
 <div className="demo-note"><span className="demo-note-dot"/><span><strong>Preview workspace</strong> &nbsp;Numbers shown are sample data for layout preview.</span></div>
 <section className="metric-grid" aria-label="Key performance indicators">{metrics.map((m,i)=><Card key={m.label} className="metric-card"><div className="metric-top"><span className="metric-label">{m.label}</span><span className={`metric-glyph glyph-${i}`}>{m.icon}</span></div><div className="metric-bottom"><strong className={i===4?'metric-value currency-value':'metric-value'}>{m.value}</strong><Badge tone={i===3?'amber':'green'}>{m.delta}</Badge></div><p className="metric-note">{m.note}</p></Card>)}</section>
 <section className="dashboard-panels"><Card className="analytics-card"><div className="panel-header"><div><p className="eyebrow">PERFORMANCE</p><h2>Sales overview</h2></div><Button variant="secondary" className="select-button">Revenue <span>⌄</span></Button></div><div className="chart-summary"><strong>{formatCurrency(4280000)}</strong><span className="chart-positive">↗ 16.8% <span>vs previous period</span></span></div><div className="chart-wrap"><div className="y-labels"><span>₹50L</span><span>₹35L</span><span>₹20L</span><span>₹5L</span></div><div className="chart"><div className="chart-gridlines"><i/><i/><i/><i/></div><div className="chart-bars">{bars.map((height,i)=><div className="bar-column" key={i}><span className={i===9?'bar bar-highlight':'bar'} style={{height:`${height}%`}}/><small>{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i]}</small></div>)}</div></div></div><div className="chart-footer"><span><i className="legend-dot"/>Revenue</span><span>Updated just now</span></div></Card>
 <Card className="pipeline-card"><div className="panel-header"><div><p className="eyebrow">OPPORTUNITIES</p><h2>Deals by segment</h2></div><button className="more-button" aria-label="More deal options">···</button></div><div className="segment-total"><div className="donut"><div><strong>148</strong><small>deals</small></div></div><div className="segment-legend">{[['Industrial chemicals','28%','seg-one'],['Specialty chemicals','24%','seg-two'],['Agrochemicals','18%','seg-three'],['Pharma intermediates','16%','seg-four'],['Other','14%','seg-five']].map(x=><p key={x[0]}><i className={`seg-dot ${x[2]}`}/>{x[0]}<span>{x[1]}</span></p>)}</div></div><div className="pipeline-foot"><span>Across 5 industry segments</span><span className="mini-link">View pipeline ↗</span></div></Card>
 <Card className="activity-card"><div className="panel-header"><div><p className="eyebrow">YOUR TEAM</p><h2>Recent activity</h2></div><button className="text-link">View all ↗</button></div><div className="activity-list">{activity.map((a,i)=><div className="activity-item" key={a.initials}><span className={`activity-avatar avatar-${i}`}>{a.initials}</span><div className="activity-copy"><p><strong>{a.name}</strong> {a.action} <b>{a.target}</b></p><small>{a.time}</small></div><span className="activity-more">···</span></div>)}</div><button className="activity-footer">View activity log <span>→</span></button></Card></section>
 <section className="bottom-callout"><div className="callout-symbol">✳</div><div><p className="eyebrow">BUILT FOR THE CHEMICAL VALUE CHAIN</p><h2>Relationships that move your business forward.</h2><p>Keep every customer, conversation, and opportunity in one clear view.</p></div><Button variant="secondary">Explore your workspace <span>→</span></Button></section><footer className="page-footer"><span>NeoCRM <span className="footer-sep">/</span> workspace preview</span><span>Frontend preview · Sample data</span></footer>
 </div>;}
