import { useCallback,useEffect,useMemo,useState } from 'react';
import { Badge } from '../components/ui/Badge';import { Button } from '../components/ui/Button';import { Card } from '../components/ui/Card';import { Input } from '../components/ui/Input';
import { ConfirmUserStatus } from '../components/users/ConfirmUserStatus';import { UserDetails } from '../components/users/UserDetails';import { UserForm } from '../components/users/UserForm';
import { PermissionGate } from '../permissions/PermissionGate';import { filterUsers } from '../users/filterUsers';import { createUser,listUsers,setUserStatus,updateUser } from '../users/userService';import { useFeedback } from '../feedback/FeedbackProvider';import { userRoles,type ManagedUser,type UserInput,type UserRole,type UserStatus } from '../users/types';
export function UsersPage(){
 const {notify}=useFeedback();
 const [users,setUsers]=useState<ManagedUser[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [statusFilter,setStatusFilter]=useState<UserStatus|'All'>('All');const [roleFilter,setRoleFilter]=useState<UserRole|'All'>('All');const [form,setForm]=useState<{mode:'create'|'edit';user?:ManagedUser}|null>(null);const [details,setDetails]=useState<ManagedUser|null>(null);const [statusTarget,setStatusTarget]=useState<ManagedUser|null>(null);const [busyStatus,setBusyStatus]=useState(false);const [feedback,setFeedback]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setUsers(await listUsers());}catch{setError('Unable to load users. Please try again.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const visibleUsers=useMemo(()=>filterUsers(users,query,statusFilter,roleFilter),[users,query,statusFilter,roleFilter]);
 async function saveUser(input:UserInput){if(form?.mode==='edit'&&form.user){const changed=await updateUser(form.user.id,input);setUsers(current=>current.map(user=>user.id===changed.id?changed:user));setFeedback('User updated successfully.');notify.success('User updated successfully.');}else{const created=await createUser(input);setUsers(current=>[created,...current]);setFeedback('User created successfully.');notify.success('User created successfully.');}}
 async function changeStatus(){if(!statusTarget)return;setBusyStatus(true);try{const changed=await setUserStatus(statusTarget.id,statusTarget.status==='Active'?'Inactive':'Active');setUsers(current=>current.map(user=>user.id===changed.id?changed:user));setFeedback(`User status changed to ${changed.status.toLowerCase()}.`);setStatusTarget(null);}catch{setError('Unable to update user status. Please try again.');notify.error('Unable to update user status. Please try again.');setStatusTarget(null);}finally{setBusyStatus(false);}}
 return <div className="page management-page"><div className="page-heading"><div><p className="eyebrow">SETTINGS <span className="heading-dot">·</span> ACCESS</p><h1>User management</h1><p className="page-subtitle">Manage users and access within your organization.</p></div><PermissionGate permission="users.create"><Button onClick={()=>setForm({mode:'create'})}>＋ Add user</Button></PermissionGate></div>
 <div className="table-toolbar"><label className="user-search"><span aria-hidden="true">⌕</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users..." aria-label="Search users by name or email"/></label><label className="filter-label">Status <select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as UserStatus|'All')}><option>All</option><option>Active</option><option>Inactive</option></select></label><label className="filter-label">Role <select value={roleFilter} onChange={e=>setRoleFilter(e.target.value as UserRole|'All')}><option>All</option>{userRoles.map(role=><option key={role}>{role}</option>)}</select></label></div>
 {feedback&&<p className="inline-feedback" role="status">{feedback}</p>}{error&&<div className="inline-error" role="alert"><span>{error}</span><Button variant="secondary" onClick={()=>void load()}>Retry</Button></div>}
 <Card className="users-card"><div className="users-card-header"><div><h2>Users <span className="count-chip">{loading?'—':visibleUsers.length}</span></h2><p>People with access to this workspace</p></div><span className="data-label">MOCK DATA</span></div>{loading?<div className="table-skeleton" role="status" aria-label="Loading users">{Array.from({length:4},(_,i)=><div className="skeleton-row" key={i}><i/><i/><i/><i/><i/></div>)}</div>:!error&&visibleUsers.length===0?<div className="empty-state"><span className="empty-mark">⌕</span><h3>No users found</h3><p>Try adjusting your search or filters.</p></div>:!error&&<div className="table-scroll"><table className="users-table"><thead><tr><th scope="col">Name</th><th scope="col">Email</th><th scope="col">Role</th><th scope="col">Status</th><th scope="col">Last active</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{visibleUsers.map(user=><tr key={user.id}><td><span className="user-name-cell"><span className="user-avatar" aria-hidden="true">{user.name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()}</span><strong>{user.name}</strong></span></td><td className="email-cell">{user.email}</td><td>{user.role}</td><td><Badge tone={user.status==='Active'?'green':'neutral'}>{user.status}</Badge></td><td className="last-active-cell">{user.lastActive}</td><td><details className="row-actions"><summary aria-label={`Actions for ${user.name}`} title="User actions">···</summary><div className="row-action-menu" role="group" aria-label={`${user.name} actions`}><button onClick={()=>setDetails(user)}>View details</button><PermissionGate permission="users.edit"><button onClick={()=>setForm({mode:'edit',user})}>Edit user</button></PermissionGate><PermissionGate permission="users.status"><button onClick={()=>setStatusTarget(user)}>{user.status==='Active'?'Deactivate':'Activate'}</button></PermissionGate></div></details></td></tr>)}</tbody></table></div>}{!loading&&!error&&<div className="table-footer">Showing {visibleUsers.length} of {users.length} users <span>Mock data · Changes are local to this session</span></div>}</Card>
 <UserForm open={Boolean(form)} mode={form?.mode??'create'} user={form?.user} onClose={()=>setForm(null)} onSubmit={saveUser}/><UserDetails user={details} onClose={()=>setDetails(null)}/><ConfirmUserStatus user={statusTarget} nextStatus={statusTarget?.status==='Active'?'Inactive':'Active'} onClose={()=>setStatusTarget(null)} onConfirm={changeStatus} busy={busyStatus}/></div>;
}




