import { useEffect, useState, type FormEvent } from 'react';
import { Button } from '../ui/Button';import { Dialog } from '../ui/Dialog';
import { userRoles,userStatuses,type ManagedUser,type UserInput,type UserRole,type UserStatus } from '../../users/types';
type Props={open:boolean;mode:'create'|'edit';user?:ManagedUser;onClose:()=>void;onSubmit:(input:UserInput)=>Promise<void>};
export function UserForm({open,mode,user,onClose,onSubmit}:Props){
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState<UserRole|' '>(' ');const [status,setStatus]=useState<UserStatus>('Active');const [errors,setErrors]=useState<Record<string,string>>({});const [saving,setSaving]=useState(false);const [submitError,setSubmitError]=useState('');
 useEffect(()=>{if(!open)return;setName(user?.name??'');setEmail(user?.email??'');setRole(user?.role??' ');setStatus(user?.status??'Active');setErrors({});setSubmitError('');},[open,user]);
 async function submit(event:FormEvent){event.preventDefault();const next:Record<string,string>={};if(!name.trim())next.name='Enter the user’s full name.';if(!email.trim())next.email='Enter an email address.';else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))next.email='Enter a valid email address.';if(role===' ')next.role='Select a role.';setErrors(next);if(Object.keys(next).length)return;setSaving(true);setSubmitError('');try{await onSubmit({name:name.trim(),email:email.trim(),role:role as UserRole,status});onClose();}catch{setSubmitError('We couldn’t save this user. Please try again.');}finally{setSaving(false);}}
 return <Dialog open={open} title={mode==='create'?'Add user':'Edit user'} onClose={onClose}><form className="management-form" onSubmit={submit} noValidate><label className="form-field"><span>Full name</span><input data-autofocus value={name} onChange={e=>setName(e.target.value)} autoComplete="name" aria-invalid={Boolean(errors.name)}/>{errors.name&&<small className="field-error">{errors.name}</small>}</label><label className="form-field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" aria-invalid={Boolean(errors.email)}/>{errors.email&&<small className="field-error">{errors.email}</small>}</label><label className="form-field"><span>Role</span><select value={role} onChange={e=>setRole(e.target.value as UserRole|' ')} aria-invalid={Boolean(errors.role)}><option value=" ">Select a role</option>{userRoles.map(item=><option key={item}>{item}</option>)}</select>{errors.role&&<small className="field-error">{errors.role}</small>}</label><label className="form-field"><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value as UserStatus)}>{userStatuses.map(item=><option key={item}>{item}</option>)}</select></label>{submitError&&<p role="alert" className="form-submit-error">{submitError}</p>}<div className="dialog-actions"><Button variant="secondary" type="button" onClick={onClose} disabled={saving}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':mode==='create'?'Create user':'Save changes'}</Button></div></form></Dialog>;
}
